### ISSUE TITLE
Upcoming 0.8 and a necessary DB update

### ISSUE THREAD

**Issue by kevinpapst** [YunoHost-Apps/kimai2_ynh#11]
Hi @anmol26s ,

I have a "warning" about the next version: there was a major problem in Kimai, regarding timezones and the records time storage. I wasn't noticed, as most of the user run Kimai in a foxed PHP environment only using the local timezone.
But now it was found and unfortunately after the update a special script needs to be executed, which will convert all existing records. 

Its further explained in this PR: https://github.com/kevinpapst/kimai2/pull/372

I wanted to share this info early, so you can think about a migration path.

Probably its safe to assume that YunoHost users did not import data from Kimai 1 manually, so it might be a simple if/else on the Kimai version and then executing that one command without any parameter?

**Comment by kevinpapst** [comment]
v0.8 was just released, see: 
- https://www.kimai.org/blog/2019/kimai-v2-release-0-8/
- https://github.com/kevinpapst/kimai2/releases/tag/0.8

**Comment by Creanimo** [comment]
Thanks for the detailed guide!
Will that fix the issue I described here? https://github.com/YunoHost-Apps/kimai2_ynh/issues/12
Any words on when v0.8 will be packed for Yunoho?

**Comment by kevinpapst** [comment]
Hi & yes, this will fix your issue.
As @anmol26s is the maintainer, we can only ask and wait that he updates his scripts for 0.8.1.
I guess he is offline or busy, as there was no response for a while.

**Comment by Creanimo** [comment]
Thanks for the answer. I wrote on the Yunohost forums. I hope he or someone else will have time for it soon. Got a project coming up that I would like to track with Kimai and would rather find new bugs than the old ones ;)

**Comment by kabums** [comment]
Something news about a renewed kimai2 package for yunohost?

**Comment by kevinpapst** [comment]
See https://github.com/YunoHost-Apps/kimai2_ynh/pull/14 
@anmol26s needs to verify and merge it

**Comment by kevinpapst** [comment]
I guess this one can be closed?

**Comment by kabums** [comment]
I agree

Am Mo., 29. Apr. 2019 um 03:29 Uhr schrieb Kevin Papst <
notifications@github.com>:
