### ISSUE TITLE
Time off by 1 hour

### ISSUE THREAD

**Issue by Creanimo** [YunoHost-Apps/kimai2_ynh#12]
Just set up Kimai through the Yunohost interface and noticed that all times are minus 1 hour off. Clients are set to "Berlin" which is my timezone. Is there anything else I have to change to get the correct time?

Btw great work with the new interface! Love it!

**Comment by kevinpapst** [comment]
@Creanimo this here is not the Kimai repository, its the YunoHost installer. 
Here is the Kimai repository: https://github.com/kevinpapst/kimai2

**Comment by kevinpapst** [comment]
@Creanimo check this thread, maybe it helps: https://github.com/kevinpapst/kimai2/issues/783

**Comment by kevinpapst** [comment]
@Creanimo this happened to other users as well ... the "customer timezone" does not change anything regarding the tracked times:
https://www.kimai.org/documentation/faq.html#recorded-times-are-wrong

You want to configure the users timezone preference:
https://www.kimai.org/documentation/user-preferences.html#timezone

@anmol26s I think you can close this issue

**Comment by Creanimo** [comment]
The issue I had was indeed fixed in 0.8.1. Since 0.8.1 is packed with an upgrade time conversion script in the Yunohost installer, it should be fixed for both past and future installations.
