### ISSUE TITLE
0.9 is released

### ISSUE THREAD

**Issue by kevinpapst** [YunoHost-Apps/kimai2_ynh#15]
See https://github.com/kevinpapst/kimai2/releases/tag/0.9

**Comment by anmol26s** [comment]
Will update this weekend. Sorry I was away.

**Comment by kevinpapst** [comment]
Any chance you could help testing the LDAP branch? I guess you initially opened the feature request to use it in combination with YunoHost, right?

**Comment by kevinpapst** [comment]
Closing in favor of #18
