### ISSUE TITLE
1.6.2 is released 

### ISSUE THREAD

**Issue by kevinpapst** [YunoHost-Apps/kimai2_ynh#18]
https://github.com/kevinpapst/kimai2/releases/tag/1.0

**Comment by dosch** [comment]
Any news on this?

**Comment by dosch** [comment]
now 1.5

**Comment by dosch** [comment]
1.6.1

https://github.com/kevinpapst/kimai2/releases/tag/1.6.1

**Comment by dosch** [comment]
1.6.2

https://github.com/kevinpapst/kimai2/releases/tag/1.6.2

**Comment by dosch** [comment]
@anmol26s [1.7 is released](https://github.com/kevinpapst/kimai2/releases/tag/1.7)
