### ISSUE TITLE
New Kimai release

### ISSUE THREAD

**Issue by kevinpapst** [YunoHost-Apps/kimai2_ynh#2]
Hi @anmol26s !

I released 0.4: https://github.com/kevinpapst/kimai2/releases/tag/0.4

There are unfortunately some special tasks required for this release, as discussed in #1 
see https://github.com/kevinpapst/kimai2/blob/master/UPGRADING.md

Any chance these can be scripted? Can I support somehow?

**Comment by kevinpapst** [comment]
@anmol26s can you create a PR for your, so I have a place to leave comments (don't want to spam the other issue)

**Comment by anmol26s** [comment]
I have merged testing to master. And the app is now to version 0.4.

Thanks for your wonderful work.
