### ISSUE TITLE
Cant sign in with user after installation

### ISSUE THREAD

**Issue by thaelke** [YunoHost-Apps/kimai2_ynh#21]
Hi, i installed yunoHost /kimai2 in a virtual mashine.

YunoHost and Kimai can be accessed via the URL

But i cant login with the admin user, i created. is there a default second admin, or where might I find the users table in order to set a new admin?

**Comment by yalh76** [comment]
Kimai wasn't really working, can you try to remove and reinstall it.

**Comment by mediaformat** [comment]
At some point since Feb 2021 SingleSignOn stopped working.
In the mean time you can reset the [admin password](https://www.kimai.org/documentation/users.html#admin-password-forgotten) using `bin/console kimai:user:password <username> <password>`
