### ISSUE TITLE
[buster] Adapt the PHP 7.x custom install / requirement

### ISSUE THREAD

**Issue by alexAubin** [YunoHost-Apps/kimai2_ynh#22]
Following the discussion started [here](https://github.com/YunoHost/issues/issues/1255#issuecomment-596254890), this app needs to be adapted both to : 
- be installable on a fresh Buster system
- make the transition smooth for people upgrading from Stretch to Buster

Currently the app relies on a custom install of PHP 7.1 / 7.2 / 7.3 which should be adapted. Imho (to be discussed and see with other app packagers after we gain more XP with this) : 
- the scripts should be adapted to use PHP 7.3 instead of 7.2
- the upgrade script should take care of the move from 7.2 to 7.3 (which for users could and should therefore happen prior to the upgrade to buster)
- we should have an if/else to install PHP 7.3 only if we're on stretch (and not on buster) [like drafted here for mastodon](https://github.com/YunoHost-Apps/pixelfed_ynh/pull/101/commits/c2f96cf3dc743ad1963926d8cd84981d59e5b816) but also need to be propagated on restore script (and maybe upgrade script)

Overall this treatment should be pretty much the same for all apps in that situation, so once we solve this for one app it should be easily applicable to other similar apps.

**Comment by kevinpapst** [comment]
@alexAubin I think we need to find a maintainer for this repo first. Are you the right person to talk to when it comes to repository permissions? 
I find it highly annoying, that nobody takes care of the package, which gives a very bad impression of Kimai. Not that I want to become the maintainer of this repo, but I could have a look for problems here and there (as I am the developer of Kimai).

**Comment by anmol26s** [comment]
@kevinpapst Sorry for not maintaining  the repo. I was little busy. I will rework on the repo and try to update it. Will need your help on it too.

**Comment by kevinpapst** [comment]
@anmol26s oh hey, there your are 😄 I don't blame you at all. You did a great job when integrating it the first time and I am thankful for it!

Its just the fact that the app integration should be a win-win for both sides. And the current situation is more like a loose-loose situation, both for Kimai and for YunoHost. Having a broken/outdated app is frustrating for YunoHost users.

And I have no clue how to reach someone that could pass on permissions to me, "just in case". As said: I don't really have time for being a maintainer here, but it would be good to know that in case of an emergency/critical bug or something similar I would be able to jump in.

**Comment by yalh76** [comment]
Well I've made a PR to upgrade the package to Kimai2 1.8 from https://github.com/kevinpapst/kimai2/releases/download/1.8/kimai-release-1.8.zip + PHP7.3 but for now. I've an error 500. And I can't figure what is missing....

![image](https://user-images.githubusercontent.com/30271971/79627829-fc0d3900-813b-11ea-8f6d-d3f2b2685b55.png)

Did I need to execute `composer` even when using the .zip release file ?

**Comment by kevinpapst** [comment]
No, executing composer shouldn't be necessary.
Are you sure that the file permissions are correct?
Anything in var/log/prod.log?
