### ISSUE TITLE
Kimai2 Install shows crrupt 

### ISSUE THREAD

**Issue by ankitdarda** [YunoHost-Apps/kimai2_ynh#26]
I am trying to install Kimai on (yunohost-buster-4.0.3-amd64-stable.iso) (yunohost-buster-4.0.3-i386-stable.iso) yunohost over the virtualbox, it kept giving me error of the corrupt source. Could not install kimai2: An error occurred inside the app installation script

**Comment by ankitdarda** [comment]
Please help!

**Comment by ankitdarda** [comment]
error log - https://paste.yunohost.org/raw/ozixibozoy

**Comment by anmol26s** [comment]
This PR should fix it. https://github.com/YunoHost-Apps/kimai2_ynh/pull/29
