### ISSUE TITLE
Homepage URL wrong in repo description

### ISSUE THREAD

**Issue by kevinpapst** [YunoHost-Apps/kimai2_ynh#27]
The mentioned URL  https://v2.kimai.org in the repository description is wrong.

Should be changed to https://www.kimai.org

This issue was already mentioned in #20 but closed without fix.

**Comment by anmol26s** [comment]
Thanks @kevinpapst 
This should fix it. https://github.com/YunoHost-Apps/kimai2_ynh/pull/29

**Comment by kevinpapst** [comment]
Thanks @anmol26s 😄 Do you have the permission to remove/fix the link here as well:

![Bildschirmfoto 2020-10-29 um 14 33 07](https://user-images.githubusercontent.com/533162/97580659-df5b9300-19f3-11eb-8ca6-725d91e5e5f8.png)

**Comment by kevinpapst** [comment]
@yalh76 can you have a look at my last screenshot? this issue was not fixed by the merge

**Comment by anmol26s** [comment]
@kevinpapst 
Thanks for pointing it out. I have changed the link.

**Comment by kevinpapst** [comment]
Awesome, thanks @anmol26s 👍
