### ISSUE TITLE
Android Tracker App API Error

### ISSUE THREAD

**Issue by leuchtrakete666** [YunoHost-Apps/kimai2_ynh#32]
i am on the latest yunohost. i need to use the tracker app, but i get "Invalid answer from API". i set API passwords for my users. to create the user i log in with each single yunohost LDAP user. unfortunetly i dont see them right away in the management gui.

furthermore i cant provide any logs. i only get "Missing Logfile".

**Comment by anmol26s** [comment]
Have you installed app on private mode or public mode?

**Comment by leuchtrakete666** [comment]
what exactly you mean with private and public mode? i dont see any option like this. i guess you talk about the yunohost app kimai while installation?

**Comment by leuchtrakete666** [comment]
would be great if i could see any logs. the doctor tab log files is just showing "Missing Logfile" and kimai2/var/log is also empty

**Comment by leuchtrakete666** [comment]
> Have you installed app on private mode or public mode?

i have installed the kimai app on yunohost disabling the option being seen by anonymous users. also i disabled the option that users can register themselfes.

**Comment by kevinpapst** [comment]
Can you open xxx/api/doc in your installation? Probably everything is good with Kimai, but you are only using a wrong URL?

Where does the message `Invalid answer from API` come from?

**Comment by leuchtrakete666** [comment]
when i open https://mydomain.my/api/doc i get straight to the login screen.

the message `Invalid answer from API` appears in the android kimai app, when i push the button "Test Settings"

**Comment by kevinpapst** [comment]
> when i open https://mydomain.my/api/doc i get straight to the login screen.

and after login? please provide as much info as possible

**Comment by leuchtrakete666** [comment]
ups, sorry i didnt try to login. 

the API Docs page apears. with all api listed.

**Comment by kevinpapst** [comment]
Two options: you entered a wrong URL in the app or your Kimai is not available from outside (private mode?) 
I don't know how YunoHost works, so I would test that as well

**Comment by kevinpapst** [comment]
There was a bug in the app: don't enter a `/` at the end of the URL!
So something like https://example.kimai.cloud or https://mydomain.my

**Comment by leuchtrakete666** [comment]
is there a port to open in firewall?

**Comment by leuchtrakete666** [comment]
the URL i entered is correct. i checked this many times.

**Comment by leuchtrakete666** [comment]
i still dont understand this private and public mode. i dont find any option for this in the installation process of kimai in yunohost.

**Comment by leuchtrakete666** [comment]
another question. is there a way to turn on loging? like i write before, there is no logfile for kimai. nor in var/www/kimai2/var/log neither in var/log

**Comment by anmol26s** [comment]
> i have installed the kimai app on yunohost disabling the option being seen by anonymous users. also i disabled the option that users can register themselfes.

This means that you are on private mode. You would not be able to see the Kimai2 page without login to the Yunohost. Please correct me if its other way around and you are on public mode. 

> is there a port to open in firewall?

No there is not need to open any port. Api is not relate to any port.

> another question. is there a way to turn on loging? like i write before, there is no logfile for kimai. nor in var/www/kimai2/var/log neither in var/log

Yes we can. As far as I can remember you have to change the value **registration** to **true** in var/www/kimai2/config/packages/local.yaml.

> another question. is there a way to turn on loging? like i write before, there is no logfile for kimai. nor in var/www/kimai2/var/log neither in var/log

Most of the times problem is in the Nginx configuration. So check the log /var/log/nginx/yourdomain.tld.error.log

**Comment by anmol26s** [comment]
@kevinpapst 
Do we have LDAP ready for Kimai2?

**Comment by kevinpapst** [comment]
Kimai supports LDAP, yes: https://www.kimai.org/documentation/ldap.html

**Comment by anmol26s** [comment]
Great, this should be implemented in Kimai2. I will test it this weekend.
And from where can we change the log file for the Kimai2?

**Comment by leuchtrakete666** [comment]
> > i have installed the kimai app on yunohost disabling the option being seen by anonymous users. also i disabled the option that users can register themselfes.
> 
> This means that you are on private mode. You would not be able to see the Kimai2 page without login to the Yunohost. Please correct me if its other way around and you are on public mode.

thats it!!!! i just installed a new instance with the anonymous option set and now it works. 

there is just the logging issue left. 

now i will try to install plugins. i hope this will work, if not you will read again from me ;)

**Comment by kevinpapst** [comment]
Log config: `config/packages/prod/monolog.yaml` - probably its changed to point to some global YunoHost location?

**Comment by anmol26s** [comment]
`probably its changed to point to some global YunoHost location?`
I think it has not changed anything. I will test it.

**Comment by anmol26s** [comment]
> thats it!!!! i just installed a new instance with the anonymous option set and now it works.
The api should be public by default despite the app being installed on private or public mode. I will fix this in next update.

**Comment by kevinpapst** [comment]
BTW: "Missing log file" doesn't mean it is not working! 
Probably there hasn't been any log message ... logs are only written upon errors.

**Comment by leuchtrakete666** [comment]
i get it. i will keep an eye on this.

thanks for you all and your help.
