### ISSUE TITLE
Login doesn't work with LDAP after upgrade to 1.17

### ISSUE THREAD

**Issue by curious-jeremy** [YunoHost-Apps/kimai2_ynh#47]
I had a version 1.11 of Kimai2 working properly. LDAP users could login with no issue.

But after an update to version 1.17, it is not possible anymore for users to login with their "yunohost" credentials (yunohost user/password). The message "Invalid credentials" is shown.
However, a "Kimai" user (a user created directly in Kimai) can login correctly (with their kimai credentials).

I can reproduce this behavior consistently: If I restore the 1.11 backup, I can login with a ldap user, but as soon as I perform the update it not possible anymore.

I tried to dig a little bit but I couldn't find anything: the upgrade runs correctly, everything in the mysql DB seems to be OK and I couldn't find any really relevant logs.

I tried what's suggested in this PR: https://github.com/YunoHost-Apps/kimai2_ynh/pull/46 but it doesn't change anything.

**Comment by ericgaspar** [comment]
#48 should fix the issue

**Comment by curious-jeremy** [comment]
Yes, I can confirm that #48 fixes this issue :+1:

**Comment by ericgaspar** [comment]
cool. closing then
