### ISSUE TITLE
Enhance description

### ISSUE THREAD

**Issue by tituspijean** [YunoHost-Apps/kimai2_ynh#5]
Hi, I was browsing the [apps list](https://yunohost.org/#/apps) (I guess it is the same in the webadmin), and came across Kimai's "non-description". 😄

https://github.com/YunoHost-Apps/kimai2_ynh/blob/1cbdff7b77e5a9d6c2197ed7a309d3cd97659e58/manifest.json#L6

I suggest something more informative like "Kimai2, open-source timetracker packaged for YunoHost".

**Comment by kevinpapst** [comment]
I would double that, as the name "Kimai" is not very descriptive. I guess we discussed that in the past @anmol26s but I can't really remember.
If its possible to change, I don't mind if you pick it from the repo or website ...
> Kimai v2 is web based Timetracker: multi-user application for time-tracking using Symfony 4 and the AdminLTE theme. Can be used by Freelancers, Agencies and Companies to track employee working-times and generate invoices.

**Comment by anmol26s** [comment]
I have updated the English version, thought English is not my native but I am limited to it only. I would appreciate if someone can translate in other languages too.
https://github.com/YunoHost-Apps/kimai2_ynh/blob/master/manifest.json#L6

**Comment by kevinpapst** [comment]
Is the description limited to a certain amount of characters?

**Comment by anmol26s** [comment]
AFAIK its not limited to number of characters.

**Comment by tituspijean** [comment]
AFAIK I don't think either, but keep in mind they are displayed in the apps list in the admin. It may be preferable to keep descriptions simple and on point. :)
