### ISSUE TITLE
Upgrade from 1.11.1 to 1.20.2 fails

### ISSUE THREAD

**Issue by curious-jeremy** [YunoHost-Apps/kimai2_ynh#57]
### Describe the bug

Upgrade from 1.11.1 to 1.20.2 fails, looks like it is due to a composer issue.
See [here](https://forum.yunohost.org/t/upgrading-kimai2-from-1-11-1-ynh1-to-1-20-2-ynh1-fails/20128) for details.

### Context

In addition to the issue reported by Ferdimator and linked above, this has been reproduced on 2 different OVH VPS, with clean and vanilla yunohost installs.

### Logs

https://paste.yunohost.org/raw/omibavawuk

**Comment by svenbrier** [comment]
Same here: https://paste.yunohost.org/raw/fuqediyobu
